version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - microservices-network

  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=RentingServiceDB;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=True;
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
